spring.application.name=payflow
spring.threads.virtual.enabled=true
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/payflow}
spring.datasource.username=${DATABASE_USER:basit}
spring.datasource.password=${DATABASE_PASSWORD:bece2018}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/{vendor}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:}
spring.logging.level.org.springframework.security=DEBUG
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
