spring.application.name=payflow
spring.threads.virtual.enabled=true
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/payflow}
spring.datasource.username=${DATABASE_USER:basit}
spring.datasource.password=${DATABASE_PASSWORD:bece2018}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration/{vendor}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWK_SET_URI:}
payflow.encryption.secret=${ENCRYPTION_SECRET:change-this-in-production-must-be-32-chars-min}
spring.logging.level.org.springframework.security=DEBUG
spring.jpa.properties.hibernate.show_sql=true
logging.file.name=${LOG_FILE:logs/payflow.log}
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=14
logging.logback.rollingpolicy.total-size-cap=250MB
logging.logback.rollingpolicy.clean-history-on-start=false
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:basitmohammed300@gmail.com}
spring.mail.password=${MAIL_PASSWORD:jpfy owkp qdmc mxyb}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
payflow.notifications.from=${MAIL_FROM:basitmohammed300@gmail.com}
